// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/feeds/index.tsx";
import * as $5 from "./routes/greet/[name].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/search.tsx";
import * as $$0 from "./islands/AddFeed.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/feeds/index.tsx": $4,
    "./routes/greet/[name].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/search.tsx": $7,
  },
  islands: {
    "./islands/AddFeed.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
